ALTER TABLE `ppr_working_mans` MODIFY COLUMN `participation` double(7,3) NOT NULL DEFAULT 1;--> statement-breakpoint
ALTER TABLE `ppr_working_mans` MODIFY COLUMN `year_plan_time` double(7,3) NOT NULL;--> statement-breakpoint
ALTER TABLE `ppr_working_mans` MODIFY COLUMN `jan_plan_time` double(7,3) NOT NULL;--> statement-breakpoint
ALTER TABLE `ppr_working_mans` MODIFY COLUMN `feb_plan_time` double(7,3) NOT NULL;--> statement-breakpoint
ALTER TABLE `ppr_working_mans` MODIFY COLUMN `mar_plan_time` double(7,3) NOT NULL;--> statement-breakpoint
ALTER TABLE `ppr_working_mans` MODIFY COLUMN `apr_plan_time` double(7,3) NOT NULL;--> statement-breakpoint
ALTER TABLE `ppr_working_mans` MODIFY COLUMN `may_plan_time` double(7,3) NOT NULL;--> statement-breakpoint
ALTER TABLE `ppr_working_mans` MODIFY COLUMN `june_plan_time` double(7,3) NOT NULL;--> statement-breakpoint
ALTER TABLE `ppr_working_mans` MODIFY COLUMN `july_plan_time` double(7,3) NOT NULL;--> statement-breakpoint
ALTER TABLE `ppr_working_mans` MODIFY COLUMN `aug_plan_time` double(7,3) NOT NULL;--> statement-breakpoint
ALTER TABLE `ppr_working_mans` MODIFY COLUMN `sept_plan_time` double(7,3) NOT NULL;--> statement-breakpoint
ALTER TABLE `ppr_working_mans` MODIFY COLUMN `oct_plan_time` double(7,3) NOT NULL;--> statement-breakpoint
ALTER TABLE `ppr_working_mans` MODIFY COLUMN `nov_plan_time` double(7,3) NOT NULL;--> statement-breakpoint
ALTER TABLE `ppr_working_mans` MODIFY COLUMN `dec_plan_time` double(7,3) NOT NULL;--> statement-breakpoint
ALTER TABLE `ppr_working_mans` MODIFY COLUMN `year_plan_norm_time` double(7,3) NOT NULL;--> statement-breakpoint
ALTER TABLE `ppr_working_mans` MODIFY COLUMN `jan_plan_norm_time` double(7,3) NOT NULL;--> statement-breakpoint
ALTER TABLE `ppr_working_mans` MODIFY COLUMN `feb_plan_norm_time` double(7,3) NOT NULL;--> statement-breakpoint
ALTER TABLE `ppr_working_mans` MODIFY COLUMN `mar_plan_norm_time` double(7,3) NOT NULL;--> statement-breakpoint
ALTER TABLE `ppr_working_mans` MODIFY COLUMN `apr_plan_norm_time` double(7,3) NOT NULL;--> statement-breakpoint
ALTER TABLE `ppr_working_mans` MODIFY COLUMN `may_plan_norm_time` double(7,3) NOT NULL;--> statement-breakpoint
ALTER TABLE `ppr_working_mans` MODIFY COLUMN `june_plan_norm_time` double(7,3) NOT NULL;--> statement-breakpoint
ALTER TABLE `ppr_working_mans` MODIFY COLUMN `july_plan_norm_time` double(7,3) NOT NULL;--> statement-breakpoint
ALTER TABLE `ppr_working_mans` MODIFY COLUMN `aug_plan_norm_time` double(7,3) NOT NULL;--> statement-breakpoint
ALTER TABLE `ppr_working_mans` MODIFY COLUMN `sept_plan_norm_time` double(7,3) NOT NULL;--> statement-breakpoint
ALTER TABLE `ppr_working_mans` MODIFY COLUMN `oct_plan_norm_time` double(7,3) NOT NULL;--> statement-breakpoint
ALTER TABLE `ppr_working_mans` MODIFY COLUMN `nov_plan_norm_time` double(7,3) NOT NULL;--> statement-breakpoint
ALTER TABLE `ppr_working_mans` MODIFY COLUMN `dec_plan_norm_time` double(7,3) NOT NULL;--> statement-breakpoint
ALTER TABLE `ppr_working_mans` MODIFY COLUMN `year_plan_tabel_time` double(7,3) NOT NULL;--> statement-breakpoint
ALTER TABLE `ppr_working_mans` MODIFY COLUMN `jan_plan_tabel_time` double(7,3) NOT NULL;--> statement-breakpoint
ALTER TABLE `ppr_working_mans` MODIFY COLUMN `feb_plan_tabel_time` double(7,3) NOT NULL;--> statement-breakpoint
ALTER TABLE `ppr_working_mans` MODIFY COLUMN `mar_plan_tabel_time` double(7,3) NOT NULL;--> statement-breakpoint
ALTER TABLE `ppr_working_mans` MODIFY COLUMN `apr_plan_tabel_time` double(7,3) NOT NULL;--> statement-breakpoint
ALTER TABLE `ppr_working_mans` MODIFY COLUMN `may_plan_tabel_time` double(7,3) NOT NULL;--> statement-breakpoint
ALTER TABLE `ppr_working_mans` MODIFY COLUMN `june_plan_tabel_time` double(7,3) NOT NULL;--> statement-breakpoint
ALTER TABLE `ppr_working_mans` MODIFY COLUMN `july_plan_tabel_time` double(7,3) NOT NULL;--> statement-breakpoint
ALTER TABLE `ppr_working_mans` MODIFY COLUMN `aug_plan_tabel_time` double(7,3) NOT NULL;--> statement-breakpoint
ALTER TABLE `ppr_working_mans` MODIFY COLUMN `sept_plan_tabel_time` double(7,3) NOT NULL;--> statement-breakpoint
ALTER TABLE `ppr_working_mans` MODIFY COLUMN `oct_plan_tabel_time` double(7,3) NOT NULL;--> statement-breakpoint
ALTER TABLE `ppr_working_mans` MODIFY COLUMN `nov_plan_tabel_time` double(7,3) NOT NULL;--> statement-breakpoint
ALTER TABLE `ppr_working_mans` MODIFY COLUMN `dec_plan_tabel_time` double(7,3) NOT NULL;--> statement-breakpoint
ALTER TABLE `ppr_working_mans` MODIFY COLUMN `year_fact_time` double(7,3) NOT NULL;--> statement-breakpoint
ALTER TABLE `ppr_working_mans` MODIFY COLUMN `jan_fact_time` double(7,3) NOT NULL;--> statement-breakpoint
ALTER TABLE `ppr_working_mans` MODIFY COLUMN `feb_fact_time` double(7,3) NOT NULL;--> statement-breakpoint
ALTER TABLE `ppr_working_mans` MODIFY COLUMN `mar_fact_time` double(7,3) NOT NULL;--> statement-breakpoint
ALTER TABLE `ppr_working_mans` MODIFY COLUMN `apr_fact_time` double(7,3) NOT NULL;--> statement-breakpoint
ALTER TABLE `ppr_working_mans` MODIFY COLUMN `may_fact_time` double(7,3) NOT NULL;--> statement-breakpoint
ALTER TABLE `ppr_working_mans` MODIFY COLUMN `june_fact_time` double(7,3) NOT NULL;--> statement-breakpoint
ALTER TABLE `ppr_working_mans` MODIFY COLUMN `july_fact_time` double(7,3) NOT NULL;--> statement-breakpoint
ALTER TABLE `ppr_working_mans` MODIFY COLUMN `aug_fact_time` double(7,3) NOT NULL;--> statement-breakpoint
ALTER TABLE `ppr_working_mans` MODIFY COLUMN `sept_fact_time` double(7,3) NOT NULL;--> statement-breakpoint
ALTER TABLE `ppr_working_mans` MODIFY COLUMN `oct_fact_time` double(7,3) NOT NULL;--> statement-breakpoint
ALTER TABLE `ppr_working_mans` MODIFY COLUMN `nov_fact_time` double(7,3) NOT NULL;--> statement-breakpoint
ALTER TABLE `ppr_working_mans` MODIFY COLUMN `dec_fact_time` double(7,3) NOT NULL;--> statement-breakpoint
ALTER TABLE `pprs_data` MODIFY COLUMN `year_fact_work` double(7,3) NOT NULL;--> statement-breakpoint
ALTER TABLE `pprs_data` MODIFY COLUMN `jan_fact_work` double(7,3) NOT NULL;--> statement-breakpoint
ALTER TABLE `pprs_data` MODIFY COLUMN `feb_fact_work` double(7,3) NOT NULL;--> statement-breakpoint
ALTER TABLE `pprs_data` MODIFY COLUMN `mar_fact_work` double(7,3) NOT NULL;--> statement-breakpoint
ALTER TABLE `pprs_data` MODIFY COLUMN `apr_fact_work` double(7,3) NOT NULL;--> statement-breakpoint
ALTER TABLE `pprs_data` MODIFY COLUMN `may_fact_work` double(7,3) NOT NULL;--> statement-breakpoint
ALTER TABLE `pprs_data` MODIFY COLUMN `june_fact_work` double(7,3) NOT NULL;--> statement-breakpoint
ALTER TABLE `pprs_data` MODIFY COLUMN `july_fact_work` double(7,3) NOT NULL;--> statement-breakpoint
ALTER TABLE `pprs_data` MODIFY COLUMN `aug_fact_work` double(7,3) NOT NULL;--> statement-breakpoint
ALTER TABLE `pprs_data` MODIFY COLUMN `sept_fact_work` double(7,3) NOT NULL;--> statement-breakpoint
ALTER TABLE `pprs_data` MODIFY COLUMN `oct_fact_work` double(7,3) NOT NULL;--> statement-breakpoint
ALTER TABLE `pprs_data` MODIFY COLUMN `nov_fact_work` double(7,3) NOT NULL;--> statement-breakpoint
ALTER TABLE `pprs_data` MODIFY COLUMN `dec_fact_work` double(7,3) NOT NULL;