import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { MainLayout } from "@/6app/Layouts";
import { getServerSession } from "next-auth";
import { LoginForm } from "@/3features/Login";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await getServerSession();
  if (!session) {
    return (
      <html lang="en">
        <body className={inter.className}>
          <AntdRegistry>
            <div className="h-screen flex justify-center">
              <LoginForm />
            </div>
          </AntdRegistry>
        </body>
      </html>
    );
  }
  return (
    <html lang="en">
      <body className={inter.className}>
        <AntdRegistry>
          <MainLayout>{children}</MainLayout>
        </AntdRegistry>
      </body>
    </html>
  );
}
