import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { MainLayout } from "@/4widgets/layouts";
import { SessionProvider } from "@/1shared/providers/sessionProvider";
import { getServerSession } from "next-auth";
import { authOptions } from "@/1shared/auth/authConfig";
import { LoginForm } from "@/3features/loginUser";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface IRootLayoutProps {
  children: React.ReactNode;
}

export default async function RootLayout(props: IRootLayoutProps) {
  const user = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={inter.className}>
        <AntdRegistry>
          <SessionProvider>
            {user ? (
              <MainLayout>{props.children}</MainLayout>
            ) : (
              <div className="h-screen flex justify-center">
                <LoginForm />
              </div>
            )}
          </SessionProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
