//перенести всё, что связано с состоянием UI или данных в redux! здесь оставить общие настройки (темы и т.д.)
//в заголовок перенести настройки, связанные с заголовком таблицы (title)??? с другой стороны, здесь хранятся настройки для vText
//vText - создать массив, в котором будут перечисленны столбы для которых текст будет вертикальным
const settings = {
  colors: {
    firstQuarter: "rgba(0,26,255,0.5)",
    secondQuarter: "rgba(1,129,16,0.5)",
    thirdQuarter: "rgba(6,180,154,0.5)",
    fourthQuarter: "rgba(255,132,0,0.5)",
    firstQuarterTransparent: "rgba(0,26,255,0.2)",
    secondQuarterTransparent: "rgba(1,129,16,0.2)",
    thirdQuarterTransparent: "rgba(6,180,154,0.2)",
    fourthQuarterTransparent: "rgba(255,132,0,0.2)",
  },
  cellSize: {
    small: { width: "30px", height: "50px" },
  },
  fonts: ["sans-serif", "Roboto"],
  fontSizes: {
    small: "1em",
    medium: "2em",
    large: "3em",
  },
  hiddenPprColumns: {
    none: [],
    planning: ["fact_work", "fact_norm_time", "fact_time"],
    fulfilling: [],
    only_work: ["plan_time", "fact_norm_time", "fact_time"],
  },
  editablePprColumns: {
    none: [],
    planning: [
      "section",
      "subsection_first",
      "location",
      "line_class",
      "measure",
      "total_count",
      "entry_year",
      "periodicity_normal",
      "last_maintenance_year",
      "periodicity_fact",
      "norm_of_time",
      "norm_of_time_document",
      "unity",
      "plan_work",
    ],
    fulfilling: ["fact_work", "fact_time"],
  },
  pprColumnSettings: {
    textareaRows: 6,
    textareaCols: 10,
    fullPlanwidthPercent: 30,
    section: {
      title: "Наименования и условия выполнения технологических операций, испытаний и измерений",
      widthPercent: 10,
      titleRowSpan: 4,
      titleColSpan: 2,
    },
    subsection_first: { title: "" },
    location: { title: "Наименование места проведения работ / тип оборудования", widthPercent: 4, titleRowSpan: 4 },
    line_class: {
      title: "Класс участка / вид технического обслуживания и ремонта",
      widthPercent: 1,
      titleRowSpan: 4,
      vText: true,
    },
    measure: { title: "Измеритель", widthPercent: 1, titleRowSpan: 4, vText: true },
    total_count: { title: "Количество измерителей (всего)", widthPercent: 1, titleRowSpan: 4, vText: true },
    entry_year: { title: "Год ввода в эксплуатацию", widthPercent: 1, titleRowSpan: 4, vText: true },
    periodicity_normal: {
      title: "Периодичность выполнения работ (в соответствии с действующими правилами)",
      widthPercent: 1,
      titleRowSpan: 4,
      vText: true,
    },
    last_maintenance_year: {
      title: "Периодичность выполнения работ (факт)",
      widthPercent: 1,
      titleRowSpan: 4,
      vText: true,
    },
    periodicity_fact: {
      title: "Дата последнего выполнения (для работ с периодичностью более 1 года)",
      widthPercent: 1,
      titleRowSpan: 4,
      vText: true,
    },
    norm_of_time: { title: "Норма времени на измеритель, чел.-ч", widthPercent: 1, titleRowSpan: 4, vText: true },
    norm_of_time_document: { title: "Обоснование нормы времени", widthPercent: 2, titleRowSpan: 4 },
    unity: { title: "Подразделение / исполнитель", widthPercent: 1, titleRowSpan: 4, vText: true },
    plan_work: { title: "кол-во", vText: true },
    plan_time: { title: "норм. время на плановый объем, чел.-ч", vText: true },
    fact_work: { title: "кол-во", vText: true },
    fact_norm_time: { title: "трудозатраты по норме времени, чел.-ч", vText: true },
    fact_time: { title: "фактические трудозатраты, чел.-ч", vText: true },
    year: { title: "Всего за год", titleColSpan: 5 },
    jan: { title: "Январь", titleColSpan: 5 },
    feb: { title: "Февраль", titleColSpan: 5 },
    mar: { title: "Март", titleColSpan: 5 },
    apr: { title: "Апрель", titleColSpan: 5 },
    may: { title: "Май", titleColSpan: 5 },
    june: { title: "Июнь", titleColSpan: 5 },
    july: { title: "Июль", titleColSpan: 5 },
    aug: { title: "Август", titleColSpan: 5 },
    sept: { title: "Сентябрь", titleColSpan: 5 },
    oct: { title: "Октябрь", titleColSpan: 5 },
    nov: { title: "Ноябрь", titleColSpan: 5 },
    dec: { title: "Декабрь", titleColSpan: 5 },
  },
};
export default settings;
export const pprStatuses = ["none", "template", "creating", "on_agreement", "on_aprove", "fulfilling", "done"];
export const pprHidingColumnsStates = ["none", "planning", "fulfilling", "only_work"];
export const pprEditableCellsStates = ["none", "planning", "fulfilling"];
export const fullMonthsList = [
  "year",
  "jan",
  "feb",
  "mar",
  "apr",
  "may",
  "june",
  "july",
  "aug",
  "sept",
  "oct",
  "nov",
  "dec",
];
export const fullInfoColumnsList = [
  "section",
  "subsection_first",
  "location",
  "line_class",
  "measure",
  "total_count",
  "entry_year",
  "periodicity_normal",
  "last_maintenance_year",
  "periodicity_fact",
  "norm_of_time",
  "norm_of_time_document",
  "unity",
];
export const fullWorkAndTimeColumnsList = ["plan_work", "plan_time", "fact_work", "fact_norm_time", "fact_time"];
export const databaseColumns = [
  "id",
  "index",
  "work_id",
  "branch",
  "subbranch",
  "section",
  "subsection_first",
  "subsection_second",
  "location",
  "line_class",
  "measure",
  "total_count",
  "entry_year",
  "periodicity_normal",
  "periodicity_fact",
  "last_maintenance_year",
  "norm_of_time",
  "norm_of_time_document",
  "plan_work",
  "plan_time",
  "fact_work",
  "fact_norm_time",
  "fact_time",
];
