import { PlannedWorkingMans } from "../model/ppr.types";

export function createNewWorkingManInstance(): PlannedWorkingMans {
  return {
    id: String(new Date().toString() + Math.random()),
    full_name: "Иванов И.И.",
    work_position: "мкс",
    is_working_man_aproved: false,
    participation: 1,
    year_plan_time: 0,
    jan_plan_time: 0,
    feb_plan_time: 0,
    mar_plan_time: 0,
    apr_plan_time: 0,
    may_plan_time: 0,
    june_plan_time: 0,
    july_plan_time: 0,
    aug_plan_time: 0,
    sept_plan_time: 0,
    oct_plan_time: 0,
    nov_plan_time: 0,
    dec_plan_time: 0,
    year_fact_time: 0,
    jan_fact_time: 0,
    feb_fact_time: 0,
    mar_fact_time: 0,
    apr_fact_time: 0,
    may_fact_time: 0,
    june_fact_time: 0,
    july_fact_time: 0,
    aug_fact_time: 0,
    sept_fact_time: 0,
    oct_fact_time: 0,
    nov_fact_time: 0,
    dec_fact_time: 0,
    year_plan_norm_time: 0,
    jan_plan_norm_time: 0,
    feb_plan_norm_time: 0,
    mar_plan_norm_time: 0,
    apr_plan_norm_time: 0,
    may_plan_norm_time: 0,
    june_plan_norm_time: 0,
    july_plan_norm_time: 0,
    aug_plan_norm_time: 0,
    sept_plan_norm_time: 0,
    oct_plan_norm_time: 0,
    nov_plan_norm_time: 0,
    dec_plan_norm_time: 0,
    year_plan_tabel_time: 0,
    jan_plan_tabel_time: 0,
    feb_plan_tabel_time: 0,
    mar_plan_tabel_time: 0,
    apr_plan_tabel_time: 0,
    may_plan_tabel_time: 0,
    june_plan_tabel_time: 0,
    july_plan_tabel_time: 0,
    aug_plan_tabel_time: 0,
    sept_plan_tabel_time: 0,
    oct_plan_tabel_time: 0,
    nov_plan_tabel_time: 0,
    dec_plan_tabel_time: 0,
  };
}
