const settings: any = {
  colors: {
    firstQuarter: "rgba(0,26,255,0.5)",
    secondQuarter: "rgba(1,129,16,0.5)",
    thirdQuarter: "rgba(6,180,154,0.5)",
    fourthQuarter: "rgba(255,132,0,0.5)",
    firstQuarterTransparent: "rgba(0,26,255,0.2)",
    secondQuarterTransparent: "rgba(1,129,16,0.2)",
    thirdQuarterTransparent: "rgba(6,180,154,0.2)",
    fourthQuarterTransparent: "rgba(255,132,0,0.2)",
  },
  cellSize: {
    small: { width: "30px", height: "50px" },
  },
  fonts: ["sans-serif", "Roboto"],
  fontSizes: {
    small: "1em",
    medium: "2em",
    large: "3em",
  },
  hiddenPprColums: {
    none: [],
    createPlan: ["unity", "yearPlanWork", "yearPlanTime", "planWork", "planTime"],
  },
  columnSettings: {
    section: { name: "Наименования и условия выполнения технологических операций, испытаний и измерений", widthPercent: 10, titleRowSpan: 4, titleColSpan: 2 },
    subsection: { name: "" },
    location: { name: "Наименование места проведения работ / тип оборудования", widthPercent: 4 },
    lineClass: { name: "Класс участка / вид технического обслуживания и ремонта", widthPercent: 1 },
    meter: { name: "Измеритель", widthPercent: 1 },
    totalCount: { name: "Количество измерителей (всего)", widthPercent: 1 },
    yearOfLaunch: { name: "Год ввода в эксплуатацию", widthPercent: 1 },
    periodicityNormal: { name: "Периодичность выполнения работ (в соответствии с действующими правилами)", widthPercent: 1 },
    periodicityFact: { name: "Периодичность выполнения работ (факт)", widthPercent: 1 },
    periodicityLast: { name: "Дата последнего выполнения (для работ с периодичностью более 1 года)", widthPercent: 1 },
    normOfTime: { name: "Норма времени на измеритель, чел.-ч", widthPercent: 1 },
    normOfTimeDocumentSource: { name: "Обоснование нормы времени", widthPercent: 4 },
    unity: { name: "Подразделение / исполнитель", widthPercent: 1 },
    planWork: { name: "кол-во", editable: true, verticalText: true, textareaCols: 10 },
    planTime: { name: "норм. время на плановый объем, чел.-ч", editable: true, verticalText: true, textareaCols: 10 },
    factWork: { name: "кол-во", editable: true, verticalText: true, textareaCols: 10 },
    factNormTime: { name: "трудозатраты по норме времени, чел.-ч", editable: true, verticalText: true, textareaCols: 10 },
    factTime: { name: "фактические трудозатраты, чел.-ч", editable: true, verticalText: true, textareaCols: 10 },
    jan: { name: "Январь" },
    feb: { name: "Февраль" },
    mar: { name: "Март" },
    apr: { name: "Апрель" },
    may: { name: "Май" },
    june: { name: "Июнь" },
    july: { name: "Июль" },
    aug: { name: "Август" },
    sept: { name: "Сентябрь" },
    oct: { name: "Октябрь" },
    nov: { name: "Ноябрь" },
    dec: { name: "Декабрь" },
  },
};
export default settings;
export const mounthListAll = ["jan", "feb", "mar", "apr", "may", "june", "july", "aug", "sept", "oct", "nov", "dec"];
export const columnListAll = [
  "section",
  "subsection",
  "location",
  "lineClass",
  "meter",
  "totalCount",
  "yearOfLaunch",
  "periodicityNormal",
  "periodicityFact",
  "periodicityLast",
  "normOfTime",
  "normOfTimeDocumentSource",
  "unity",
  "planWork",
  "planTime",
  "factWork",
  "factNormTime",
  "factTime",
];
